name: flutter_stream_friends_example
description: A demo of the flutter_stream_friends functionality
dependencies:
  flutter:
    sdk: flutter
  flutter_stream_friends:
    path: ../
  rxdart: 0.11.0

flutter:
  uses-material-design: true

