name: flutter_stream_friends
description: Flutter's great. Streams are great. Let's mingle.
version: 0.1.0
author: brian.egan <brian@brianegan.com>
homepage: https://gitlab.com/brianegan/flutter_stream_friends

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  flutter_test:
    sdk: flutter
